### PR TITLE
adding a post and a picture for IETF121 post

### PR DESCRIPTION
**Pull request by yryo617**
This pull request contains:
- A new directories ```assets/images/``` to hold pictures 
- two pictures by the venue 
- A very short post summarising IETF121

### CODE REVIEW

**Comment by csperkins** [comment]
I was going to write a separate post about what I did at IETF. Can you say more about your talk, maybe with a link to the slides, and what you found interesting/useful at the meeting?

**Comment by yryo617** [comment]
No problem, will do that!

**Comment by csperkins** [comment]
Thanks – I rearranged things a little; hopefully didn't break anything.

**Comment by yryo617** [comment]
Looks great, thank you.

**Pull request merged**
